### ISSUE TITLE
Translations of CMB2 fields are not applied

### ISSUE THREAD

**Issue by jessor** [UkuuLogic/ukuupeople-the-simple-crm#1]
Since the Issues part of this repository is active I'll try my luck ;)

Translations of any translated string in the file `custom-fields.php` will not be applied when displaying in the frontend.

``` <?php
$prefix = 'wpcf-';
$customterm = array(
  'fields' =>array(
    'first-name' => array(
      'name' => __( 'First Name*', 'UkuuPeople' ),
```

**Comment by natewilldo** [comment]
Included in latest release. Thanks for submitting this!

**Comment by jessor** [comment]
I don't see any changes in the repository as to why/how this should work now (and it doesn't work with languages/UkuuPeople-xx_XX.mo although the strings are included).
