### ISSUE TITLE
Why are there 2 x's for closing this pop-up?

### ISSUE THREAD

**Issue by TitaniaPorter** [UkuuLogic/ukuupeople-the-simple-crm#100]
This is on the QuickAdd TouchPoint Dashlet > Add Assignee

<img width="619" alt="double x" src="https://cloud.githubusercontent.com/assets/25489988/24528953/939f4ba6-156e-11e7-9064-78d5b985d0ff.png">

**Comment by suniltorase** [comment]
This is fixed in #109
