### ISSUE TITLE
Capitalize and delete

### ISSUE THREAD

**Issue by TitaniaPorter** [UkuuLogic/ukuupeople-the-simple-crm#104]
Capitalize each word and delete the dots
<img width="393" alt="switch" src="https://cloud.githubusercontent.com/assets/25489988/24564219/c35a05d6-1616-11e7-87a6-f019a057ef84.png">

Capitalize P in TouchPoint and T in Type and delete the dots
<img width="714" alt="switch order" src="https://cloud.githubusercontent.com/assets/25489988/24564245/e00a0320-1616-11e7-981e-22af7a915b10.png">

**Comment by suniltorase** [comment]
This is fixed in #107
