### ISSUE TITLE
Quick Add TouchPoint Now Missing...

### ISSUE THREAD

**Issue by TitaniaPorter** [UkuuLogic/ukuupeople-the-simple-crm#105]
...multiple assignees option. It seems to have disappeared in the latest commit.

<img width="448" alt="more than one assignee" src="https://cloud.githubusercontent.com/assets/25489988/24565724/23d74ec8-161c-11e7-8f63-365de59af54e.png">

**Comment by suniltorase** [comment]
This is fixed in #107
