### ISSUE TITLE
Bulk Edit and Quick Edit Options

### ISSUE THREAD

**Issue by TitaniaPorter** [UkuuLogic/ukuupeople-the-simple-crm#26]
There are unnecessary options in the bulk and quick edit windows for People. Get rid of Status, Date, and Password options. If you want more options to add, try Privacy Settings and Related Organization.

The Tribes, Tags, and Contact Type options are good and should remain.

![bulk edit - humans](https://cloud.githubusercontent.com/assets/25489988/22847034/3228ccfa-efb0-11e6-9eb6-f865f24f77c4.jpg)
![quick edit humans](https://cloud.githubusercontent.com/assets/25489988/22847037/390bd364-efb0-11e6-9782-ea479e40d6e8.jpg)
![revised quick edit fields](https://cloud.githubusercontent.com/assets/25489988/22847039/3da43074-efb0-11e6-9419-677f990a72fe.jpg)

**Comment by suniltorase** [comment]
this is fixed in #30
