### ISSUE TITLE
Should say "Assigned To"

### ISSUE THREAD

**Issue by TitaniaPorter** [UkuuLogic/ukuupeople-the-simple-crm#27]
The Quick Add TouchPoint Assignee popup window says **TouchPoint Contact**. It should say **Assigned To**
![should say assigned to](https://cloud.githubusercontent.com/assets/25489988/22847820/4f985dd2-efb5-11e6-8e49-91389ce12265.jpg)

**Comment by suniltorase** [comment]
Label updated. Fixed in #31
