### ISSUE TITLE
Visual Problems with the TouchPoint Screen

### ISSUE THREAD

**Issue by TitaniaPorter** [UkuuLogic/ukuupeople-the-simple-crm#32]
1. Should be spelled TouchPoint
2. This should not look like a clickable button.
3. Calendar is too crowded against the box.

![visual errors](https://cloud.githubusercontent.com/assets/25489988/22954302/4a139948-f2db-11e6-932c-e985104129bb.jpg)

**Comment by suniltorase** [comment]
1. Label updated. Fixed in #33 
2. This is developed as per design.
3. I don't see this behavior. Can you please make sure the browser zooming is not enabled.

**Comment by TitaniaPorter** [comment]
It is not enabled. It's the view I get on my 13" screen laptop, chrome browser, no zoom. However, font size is set to Medium. Is that a problem?

![zoom not enabled](https://cloud.githubusercontent.com/assets/25489988/22982432/b90d2204-f364-11e6-983a-85e6b3e46471.jpg)
