### ISSUE TITLE
Attachments for TouchPoints Broken

### ISSUE THREAD

**Issue by TitaniaPorter** [UkuuLogic/ukuupeople-the-simple-crm#38]
1. Attachments sent via GravityForms/Ukuu TouchPoint Feed are broken.

![attachment 1](https://cloud.githubusercontent.com/assets/25489988/23436199/428231d6-fdcf-11e6-9244-bda1f5e5c24d.jpg)

2. Adding attachments to QuickAdd TouchPoints is broken. I add a file, click "Save Changes," and then get this blank screen. Nothing gets added to the TouchPoint.

![attachment 2](https://cloud.githubusercontent.com/assets/25489988/23436315/afa319a6-fdcf-11e6-9b0b-3f17b88b6bfe.jpg)

**Comment by TitaniaPorter** [comment]
This is still broken in the latest version.

**Comment by suniltorase** [comment]
1. Attachments are working fine. We checked with Gravity Form Version : 2.1.0.1 and Ukuu Gravity Forms Version : 1.0.5

2. Can you please make sure that you are following the steps below to add a file:
- Click to Upload Attachments
- Select file
- Click on "file URL" button
- Click on "Add to touchpoint" button
- Create touchpoint

**Comment by TitaniaPorter** [comment]
Okay, so I was doing it wrong. Why can't it work just like when I do it
from the TouchPoints screen? (See attached video).

**Comment by suniltorase** [comment]
@TitaniaPorter - Attachment (video) is missing.
