### ISSUE TITLE
Assign TouchPoint List Broken

### ISSUE THREAD

**Issue by TitaniaPorter** [UkuuLogic/ukuupeople-the-simple-crm#39]
When Nate first set up this new staging site, I was able to assign a touchpoint to myself and sync it with GoogleCalendar.

However, since testing the Gravity Forms Addon, I am still part of the Our Team tribe, but can no longer assign touchpoints to myself.

Here is a view of me in the list of "Our Team" members. (Notice that there is no blue dot beside my name like there is for the other contact records.)

![on our team tribe](https://cloud.githubusercontent.com/assets/25489988/23437199/d5cbc850-fdd2-11e6-974d-8dcc9dbb5b7d.jpg)

And here are my only options for assigning touchpoints.

![not on our team list](https://cloud.githubusercontent.com/assets/25489988/23437239/f74d6bbe-fdd2-11e6-9a84-eb2d3bd31b58.jpg)

I deactivated Gravity Forms and Ukuu Gravity Forms Addon and refreshed, but there has been no change.

Is this because I previewed a GravityForm I created, and filled it out with that same name and email address? That created a duplicate record of myself. I deleted the duplicate, but that didn't change anything.

**Comment by TitaniaPorter** [comment]
This can now be closed.

**Comment by suniltorase** [comment]
Can you please make sure that your contact has been marked only for "Individual"
