### ISSUE TITLE
Quick Edit Individual/Organization

### ISSUE THREAD

**Issue by natewilldo** [UkuuLogic/ukuupeople-the-simple-crm#40]
I deleted UkuuCRM and all plugins. 
Installed latest versions of everything. 
Deleted all prior contact records except Nate and Titania. 
Imported 30 new records as Individuals.
When I view the People Dashboard, the contacts are marked with a blue dot as Individuals.
However, in Quick Edit, there is nothing marked at all.
It should have a checkmark, showing these are already labeled as Individuals.
Also, there should be a place in the contact record to edit/change an Individual to an Organization or the other way around.
![quick edit ind-org](https://cloud.githubusercontent.com/assets/5235216/23525573/8da981ec-ff54-11e6-8487-6ffeb2400770.jpg)

**Comment by suniltorase** [comment]
This is fixed in #46
