### ISSUE TITLE
Quick Edit Errors

### ISSUE THREAD

**Issue by TitaniaPorter** [UkuuLogic/ukuupeople-the-simple-crm#41]
I clicked Quick Edit under Nate's name.
1. The contact name disappeared.
2. He is part of "Our Team" Tribe, but that box isn't checkmarked here in Quick Edit.
3. He is an "Individual," but that box isn't marked here.

![quick edit errors](https://cloud.githubusercontent.com/assets/25489988/23526649/73cbd8de-ff58-11e6-83d6-7ec6d4cb82f6.jpg)

**Comment by suniltorase** [comment]
This is fixed in #46 . Expects the "The contact name disappeared" - actually it's coming from core files of WordPress.
