### ISSUE TITLE
Deactivate Problem

### ISSUE THREAD

**Issue by TitaniaPorter** [UkuuLogic/ukuupeople-the-simple-crm#42]
I tried to deactivate all the Ukuu plugins at once with the bulk edit option. When I clicked Apply, this message came up with no way to affirm. I clicked Enter, but nothing happened.

![deactivate error](https://cloud.githubusercontent.com/assets/25489988/23572182/f8a0f050-0032-11e7-8569-36894bd4ea45.jpg)

**Comment by suniltorase** [comment]
The issue has been fixed. There was an issue with UkuuImport and ukuugoogleapp while activating and deactivating this 2 plugins.
A related PR is submitted.
1. https://github.com/UkuuLogic/ukuuimport/pull/36
2. https://github.com/UkuuLogic/ukuugooglecalendar/pull/37

**Comment by TitaniaPorter** [comment]
I think the new add-ons are about ready to go!

Here are links to the remaining issues. Some of them are already resolved,
I believe, but are still marked as "Open."

https://github.com/UkuuLogic/ukuureminder/issues/1
https://github.com/UkuuLogic/ukuuimport/issues/35
https://github.com/UkuuLogic/ukuuimport/issues/34
https://github.com/UkuuLogic/ukuugooglecalendar/issues/36
https://github.com/UkuuLogic/ukuupeople-the-simple-crm/issues/41
https://github.com/UkuuLogic/ukuupeople-the-simple-crm/issues/40
https://github.com/UkuuLogic/ukuupeople-the-simple-crm/issues/38c
https://github.com/UkuuLogic/ukuupeople-the-simple-crm/issues/38
https://github.com/UkuuLogic/ukuupeople-the-simple-crm/issues/37

Thank you!
Let me know what else I should be doing on my end.

-Titania
