### ISSUE TITLE
Extra Space Between TouchPoints on Dashboard

### ISSUE THREAD

**Issue by TitaniaPorter** [UkuuLogic/ukuupeople-the-simple-crm#47]
I added these 2 new TouchPoints this morning and notice there's an extra space under each one. Would that be hard to fix?

![touchpoint spacing](https://cloud.githubusercontent.com/assets/25489988/23714709/d71a92e0-03ef-11e7-8328-7cf8942556e6.jpg)

**Comment by TitaniaPorter** [comment]
I'm sorry. After adding another TouchPoint with a very short Subject Line, I realize that's what's making the extra space. Perhaps so there is room enough for the Edit/Quick Edit options beneath the title?

**Comment by subhashuyadav** [comment]
Row height is set by WordPress so we can't do anything much.
