### ISSUE TITLE
Delete View Post Message

### ISSUE THREAD

**Issue by TitaniaPorter** [UkuuLogic/ukuupeople-the-simple-crm#49]
When I create a new TouchPoint, this View Post message shows at the top of the screen. Can we delete that?
![delete view post message](https://cloud.githubusercontent.com/assets/25489988/23731765/f2bf8f6a-0434-11e7-8d1a-0eb55de7504d.jpg)

**Comment by suniltorase** [comment]
We have updated the messages and not deleted. Please confirm the same.
Fixed in #57
