### ISSUE TITLE
Error Message with latest commit

### ISSUE THREAD

**Issue by TitaniaPorter** [UkuuLogic/ukuupeople-the-simple-crm#52]
https://github.com/UkuuPeople/ukuupeople-the-simple-crm.git

I uploaded the latest UkuuPeople master, and I got this warning message. I thought it was the server, so I loaded it on a different server, and it has the exact same message.

![warning message](https://cloud.githubusercontent.com/assets/25489988/23768661/5ced3a48-04d2-11e7-80a5-7f4301c1fb8a.jpg)

**Comment by TitaniaPorter** [comment]
Sorry. Dan says both sites are on the same server. So I guess I was wrong on that.

**Comment by subhashuyadav** [comment]
The error is related to MySQL settings on the staging server. It's not related to UkuuPeople.
