### ISSUE TITLE
Quick Edit - People

### ISSUE THREAD

**Issue by TitaniaPorter** [UkuuLogic/ukuupeople-the-simple-crm#53]
This is working! So nice :)

How hard it would it be to re-order these, so they are in a row across instead of down? More compact?

![quick edit humans view](https://cloud.githubusercontent.com/assets/25489988/23770125/7423d6d6-04d7-11e7-98df-acbb66d6a0c9.jpg)

**Comment by subhashuyadav** [comment]
This is by default generated by Wordpress so we cannot change the layout easily.
