### ISSUE TITLE
Quick Edit - TouchPoints

### ISSUE THREAD

**Issue by TitaniaPorter** [UkuuLogic/ukuupeople-the-simple-crm#54]
Is it too late to add Complete/Cancel/Scheduled status options to the Quick Edit here? It seems that would be a great one to have access to.

![quick edit touchpoint](https://cloud.githubusercontent.com/assets/25489988/23770200/cd0d8e36-04d7-11e7-9b1b-21c65cd15313.jpg)

**Comment by subhashuyadav** [comment]
This is fixed in https://github.com/UkuuPeople/ukuupeople-the-simple-crm/pull/69
