### ISSUE TITLE
Visual Bar Missing From People and TouchPoint Dashbboards

### ISSUE THREAD

**Issue by TitaniaPorter** [UkuuLogic/ukuupeople-the-simple-crm#58]
Since the last commit, there's no bar showing how many ind/orgs are in the system, nor the types of TouchPoints.

**Comment by subhashuyadav** [comment]
Seems to be working fine :
![touchpoint-visualbar](https://cloud.githubusercontent.com/assets/5929769/23996271/d15a754e-0a72-11e7-94f8-61902dad134c.png)
![ukuupeople-visualbar](https://cloud.githubusercontent.com/assets/5929769/23996272/d15dc2c6-0a72-11e7-952a-c0979b9e9a69.png)
