### ISSUE TITLE
Add New Contact Selection

### ISSUE THREAD

**Issue by TitaniaPorter** [UkuuLogic/ukuupeople-the-simple-crm#60]
1.  The extra line that's been added to the Ukuu Menu "Add New Contact" saves a step (which I like). But Nate doesn't like it there because he feels it will become cluttered. (Because we will have people wanting "Add New TouchPoint" for the TouchPoints or "Add New Tribe" for Settings, etc.)

So, maybe it could be a sub-menu, when you hover your mouse over People?

Or else just get rid of it.

![add new contact](https://cloud.githubusercontent.com/assets/25489988/23877839/4bacc5f8-0812-11e7-97ed-7176ad34c9c7.jpg)

**Comment by subhashuyadav** [comment]
It is not possible in Wordpress to add submenu inside submenu, so we removed the "Add New Contact" option https://github.com/UkuuPeople/ukuupeople-the-simple-crm/pull/61.
