### ISSUE TITLE
Should be in alphabetical order

### ISSUE THREAD

**Issue by TitaniaPorter** [UkuuLogic/ukuupeople-the-simple-crm#63]
In the Report options - Organization Members: The Organizations should be listed in alphabet order.

![report - orgs should be in alphabetical order](https://cloud.githubusercontent.com/assets/25489988/24024942/2e7f70b4-0a85-11e7-9e5c-719b9534dc07.jpg)

**Comment by subhashuyadav** [comment]
This is fixed in https://github.com/UkuuPeople/ukuuimport/pull/38
