### ISSUE TITLE
Date of Birth?

### ISSUE THREAD

**Issue by TitaniaPorter** [UkuuLogic/ukuupeople-the-simple-crm#64]
I pulled in a few contacts with birthdates via a CSV Import of contacts. Here is how the date shows up in the 1. Date of Birth field, 
2. in the information box at he top of the contact record, 
3. in a report, 
4. and on an export of that same report

![date of birth](https://cloud.githubusercontent.com/assets/25489988/24025323/ae340494-0a87-11e7-8165-a5b9b4524369.jpg)![date of birth 2](https://cloud.githubusercontent.com/assets/25489988/24025324/ae3575ea-0a87-11e7-98d5-cfdab5e101ea.jpg)
![date of birth - report](https://cloud.githubusercontent.com/assets/25489988/24025322/ae335666-0a87-11e7-9aa0-484c032b97cf.jpg)

**Comment by subhashuyadav** [comment]
This is fixed in https://github.com/UkuuPeople/ukuuimport/pull/39
