### ISSUE TITLE
Error when installing and activating UkuuPeople

### ISSUE THREAD

**Issue by natewilldo** [UkuuLogic/ukuupeople-the-simple-crm#70]
I now get this error when installing and activating UkuuPeople. (Tested on Bluehost, Linode, and Servint)
![image](https://cloud.githubusercontent.com/assets/5235216/24230450/c6c6aa9a-0f44-11e7-8786-f42b1e5d2226.png)

**Comment by subhashuyadav** [comment]
This is fixed in https://github.com/UkuuPeople/ukuupeople-the-simple-crm/pull/73
