### ISSUE TITLE
Menu Order

### ISSUE THREAD

**Issue by natewilldo** [UkuuLogic/ukuupeople-the-simple-crm#72]
When addons are installed they should not fall below Settings and Add-ons. Settings and Add-ons should always be at the bottom and People and TouchPoints should always be at the top of the list.

![image](https://cloud.githubusercontent.com/assets/5235216/24230870/f8df6fb0-0f46-11e7-8483-ff6e90558858.png)

**Comment by subhashuyadav** [comment]
This is fixed in https://github.com/UkuuPeople/ukuupeople-the-simple-crm/pull/74
