### ISSUE TITLE
Please capitalize P in TouchPoint and C in Create.

### ISSUE THREAD

**Issue by TitaniaPorter** [UkuuLogic/ukuupeople-the-simple-crm#90]
Please capitalize P in TouchPoint and C in Create.

<img width="648" alt="2017-03-30_13-31-46" src="https://cloud.githubusercontent.com/assets/25489988/24521363/861bdc96-1551-11e7-9ab3-2151d39327b2.png">

**Comment by suniltorase** [comment]
This is fixed in #102
