### ISSUE TITLE
Capitalization and Selection Issues

### ISSUE THREAD

**Issue by TitaniaPorter** [UkuuLogic/ukuupeople-the-simple-crm#91]
Please capitalize 3 circled letters.
Could the first box - TouchPoint Type Selection - be where the cursor goes by default? That way I could fill out the fields in order.

<img width="764" alt="select touchpoint type first" src="https://cloud.githubusercontent.com/assets/25489988/24521517/0bf144d2-1552-11e7-9f4c-15041453bf2e.png">

**Comment by suniltorase** [comment]
1. Capitalization of letters is fixed in #102 
2. We are not doing any specific action on this form, The focus set on the field is by default by the browser.

**Comment by TitaniaPorter** [comment]
That makes sense.

What about changing the order of the fields to match the QuickAdd TouchPoint?

<img width="714" alt="switch order" src="https://cloud.githubusercontent.com/assets/25489988/24564008/15d7a38c-1616-11e7-9831-63ba0a65f629.png">

<img width="393" alt="switch" src="https://cloud.githubusercontent.com/assets/25489988/24564018/1fe7de5a-1616-11e7-9a4e-784ec4147a3a.png">

**Comment by suniltorase** [comment]
This is fixed in #110
