### ISSUE TITLE
Can't Select a File

### ISSUE THREAD

**Issue by TitaniaPorter** [UkuuLogic/ukuupeople-the-simple-crm#93]
Nothing happens when I click Select. I can only drag and drop for new files.
<img width="932" alt="won t open on select" src="https://cloud.githubusercontent.com/assets/25489988/24522327/d73b2fca-1554-11e7-9f23-d924e1b1eb3e.png">

**Comment by suniltorase** [comment]
We were not able to replicate this issue. Can you please be more specific on the steps or the environment, to replicate the same.

**Comment by TitaniaPorter** [comment]
Okay, so this must not be an UkuuPeople problem. I went to create a new post and tried to insert media there, and it also doesn't work.
