### ISSUE TITLE
Attachment from Dashlet

### ISSUE THREAD

**Issue by TitaniaPorter** [UkuuLogic/ukuupeople-the-simple-crm#95]
Why can't we add an attachment from the Quick Add Dashlet in the same way we do it from the main dashboard?
<img width="808" alt="add attachment from dashlet" src="https://cloud.githubusercontent.com/assets/25489988/24523022/42a820fe-1557-11e7-9694-a7407d3dbb54.png">

**Comment by suniltorase** [comment]
Now the attachment upload from the Quick Add Dashlet uses the same UI as in the main dashboard.
This is fixed in #111
