### ISSUE TITLE
Disappearing Attachments?

### ISSUE THREAD

**Issue by TitaniaPorter** [UkuuLogic/ukuupeople-the-simple-crm#96]
This attachment was added from Quick Add Dashlet. It shows at the top but not at the bottom.
<img width="793" alt="disappearing attachments" src="https://cloud.githubusercontent.com/assets/25489988/24523377/7921a15e-1558-11e7-8680-91917440d2bf.png">

Now I added another attachment from inside this TouchPoint. It shows both at the top and the bottom.
<img width="834" alt="mismatch" src="https://cloud.githubusercontent.com/assets/25489988/24523555/07babaf4-1559-11e7-83fe-79ea80cb0633.png">

**Comment by subhashuyadav** [comment]
We are not able to replicate this issue. Need more specifics to replicate this issue
