### ISSUE TITLE
Time Sliders? I like the "now" selection option!

### ISSUE THREAD

**Issue by TitaniaPorter** [UkuuLogic/ukuupeople-the-simple-crm#97]
I don't really like these sliders for selecting the time. But I sure do like the NOW button!

<img width="537" alt="time sliders" src="https://cloud.githubusercontent.com/assets/25489988/24523710/99b96036-1559-11e7-99b4-651bba357870.png">

**Comment by suniltorase** [comment]
This is default UI for time selection for the datepicker plugin that we use in UkuuPeople.
