### ISSUE TITLE
When I select a color for a TouchPoint Type...

### ISSUE THREAD

**Issue by TitaniaPorter** [UkuuLogic/ukuupeople-the-simple-crm#99]
...it should clear that color selection out once I click the "Add New TouchPoint Type" button. 
<img width="414" alt="touchpoint type clear selection" src="https://cloud.githubusercontent.com/assets/25489988/24527684/e2701b94-1568-11e7-9e18-5184e5713fd7.png">

**Comment by suniltorase** [comment]
This might be an issue in CMB2 plugin, that we use internally to build this filed.

**Comment by TitaniaPorter** [comment]
Does that mean it can't be changed?
